FROM registry.access.redhat.com/ubi8/ubi

RUN dnf -y install sudo pkg-config vim make gdb \
    curl git openssh-clients \
    gcc-gfortran gcc-c++ \
    openmpi-devel openmpi \
 && ln -s /usr/lib64/openmpi/bin/orted /usr/bin/orted

ENV PATH="${PATH}:/usr/lib64/openmpi/bin/"

RUN git clone $SPECFEM_GIT_REPO -b $SPECFEM_GIT_BRANCH --depth 1 /app \
 && echo "$(date) | Cloned $SPECFEM_GIT_REPO branch $SPECFEM_GIT_BRANCH (git rev-parse --short HEAD)" >> /app/oc.build.log \
 && rm -rf /app/.git